#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# setup-udev.sh — Install a udev rule for WebUSB access on Linux
#
# Default target device: VID=413D  PID=2107
# Usage:
#   sudo ./setup-udev.sh                     # use defaults
#   sudo ./setup-udev.sh 413d 2107           # explicit VID PID
#   sudo VID=413d PID=2107 ./setup-udev.sh   # via env vars
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ── Defaults ──────────────────────────────────────────────────────────────────
DEFAULT_VID="413d"
DEFAULT_PID="2107"

# ── Resolve VID / PID (CLI args > env vars > defaults) ───────────────────────
VID="${1:-${VID:-$DEFAULT_VID}}"
PID="${2:-${PID:-$DEFAULT_PID}}"

# Normalise to lowercase, strip optional "0x" prefix
VID="${VID#0x}"; VID="${VID#0X}"; VID="${VID,,}"
PID="${PID#0x}"; PID="${PID#0X}"; PID="${PID,,}"

# ── Validate ──────────────────────────────────────────────────────────────────
if [[ ! "$VID" =~ ^[0-9a-f]{4}$ ]] || [[ ! "$PID" =~ ^[0-9a-f]{4}$ ]]; then
  echo "ERROR: VID and PID must be 4 hex digits (e.g. 413d 2107)." >&2
  exit 1
fi

# ── Must run as root ──────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root (use sudo)." >&2
  exit 1
fi

# ── Paths ─────────────────────────────────────────────────────────────────────
RULES_DIR="/etc/udev/rules.d"
RULES_FILE="${RULES_DIR}/99-webusb-${VID}${PID}.rules"

# ── Write rule ────────────────────────────────────────────────────────────────
echo "Installing udev rule for VID=${VID} PID=${PID} ..."

cat > "$RULES_FILE" <<EOF
# WebUSB access rule — generated by setup-udev.sh
# Device: VID=${VID^^} PID=${PID^^}
# Allows members of the 'plugdev' group to access this USB device
# without requiring root privileges (needed for WebUSB in Chrome/Edge).
SUBSYSTEM=="usb", ATTRS{idVendor}=="${VID}", ATTRS{idProduct}=="${PID}", MODE="0664", GROUP="plugdev"
EOF

echo "  Written: ${RULES_FILE}"

# ── Reload udev ───────────────────────────────────────────────────────────────
echo "Reloading udev rules ..."
udevadm control --reload-rules
udevadm trigger
echo "  udev rules reloaded."

# ── Ensure current user is in plugdev ────────────────────────────────────────
# When run via sudo, SUDO_USER holds the original username.
REAL_USER="${SUDO_USER:-}"

if [[ -n "$REAL_USER" ]]; then
  if id -nG "$REAL_USER" | grep -qw plugdev; then
    echo "  User '${REAL_USER}' is already in the 'plugdev' group."
  else
    echo "Adding '${REAL_USER}' to the 'plugdev' group ..."
    usermod -aG plugdev "$REAL_USER"
    echo "  Done. You must log out and back in for the group change to take effect."
  fi
else
  echo "NOTE: Could not determine the invoking user."
  echo "      Run manually if needed:  sudo usermod -aG plugdev \$USER"
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Setup complete for device ${VID^^}:${PID^^}"
echo ""
echo " Next steps:"
echo "   1. Replug the USB device."
echo "   2. If you were just added to 'plugdev', log out and back in first."
echo "   3. Open Chrome/Edge and use WebUSB Explorer."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
